# Starter , Train Test Split and Missing Value Handling

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('titanic_data_updated.csv')

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,no,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,yes,first,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,yes,third,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,yes,first,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,no,third,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,no,second,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,yes,first,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,no,third,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,yes,first,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,no,third,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [4]:
df.shape

print(f"Total potential features :{df.shape[1]}")
print(f"Total sample data :{df.shape[0]}")

Total potential features :12
Total sample data :891

In [3]:
df.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
269,270,yes,first,"Bissette, Miss. Amelia",female,35.0,0,0,PC 17760,135.6333,C99,S
714,715,no,second,"Greenberg, Mr. Samuel",male,52.0,0,0,250647,13.0000,NaN,S
114,115,no,third,"Attalah, Miss. Malake",female,17.0,0,0,2627,14.4583,NaN,C
460,461,yes,first,"Anderson, Mr. Harry",male,48.0,0,0,19952,26.5500,E12,S
489,490,yes,third,"Coutts, Master. Eden Leslie ""Neville""",male,9.0,1,1,C.A. 37671,15.9000,NaN,S
572,573,yes,first,"Flynn, Mr. John Irwin (""Irving"")",male,36.0,0,0,PC 17474,26.3875,E25,S
419,420,no,third,"Van Impe, Miss. Catharina",female,10.0,0,2,345773,24.1500,NaN,S
427,428,yes,second,"Phillips, Miss. Kate Florence (""Mrs Kate Louis...",female,19.0,0,0,250655,26.0000,NaN,S
177,178,no,first,"Isham, Miss. Ann Elizabeth",female,50.0,0,0,PC 17595,28.7125,C49,C
14,15,no,third,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S

## Feature Engineering

Step:
1. If Target column does not have relation, delete those
2. Choose Feature Column and Target Column in separate data frame
3. Train Test Split
4. Missing values handling
5. Outliner (abnormal) detection data finding and cap it in a range or delete it.
6. Encode Categorical Column. Category to Numerical
7. Numerical Column Scaling
8. Feature Creation

## Train Test Split

## Numerical Missing Value Imputation with Pandas

## Numerical Missing Values Imputation using Simple Imputer

## Categorical Value Imputation with Mode Value

## Categorical Value Imputation with Missing string and Indicator

##