# Titanic Survival Prediction

In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder,LabelEncoder,StandardScaler,MinMaxScaler

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer


from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score,recall_score

## 1. Data Loading and Initial Exploration

In [2]:
# Load pandas DataFrame
df = pd.read_csv("titanic_data_updated.csv")

# to see what the data looks like
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
776,777,no,third,"Tobin, Mr. Roger",male,NaN,0,0,383121,7.7500,F38,Q
691,692,yes,third,"Karun, Miss. Manca",female,4.0,0,1,349256,13.4167,NaN,C
113,114,no,third,"Jussila, Miss. Katriina",female,20.0,1,0,4136,9.8250,NaN,S
300,301,yes,third,"Kelly, Miss. Anna Katherine ""Annie Kate""",female,NaN,0,0,9234,7.7500,NaN,Q
354,355,no,third,"Yousif, Mr. Wazli",male,NaN,0,0,2647,7.2250,NaN,C

In [3]:
df['Cabin'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: Cabin
Non-Null Count  Dtype
--------------  -----
204 non-null    object
dtypes: object(1)
memory usage: 7.1+ KB

## 2. Feature Engineering

In [4]:
df['Family_Size'] = df['SibSp'] + df['Parch'] + 1
df['Cabin'] = df['Cabin'].fillna("Missing")

df['Deck'] = df['Cabin'].astype(str).str[0]
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Deck
835,836,yes,first,"Compton, Miss. Sara Rebecca",female,39.0,1,1,PC 17756,83.1583,E49,C,3,E
777,778,yes,third,"Emanuel, Miss. Virginia Ethel",female,5.0,0,0,364516,12.4750,Missing,S,1,M
750,751,yes,second,"Wells, Miss. Joan",female,4.0,1,1,29103,23.0000,Missing,S,3,M
685,686,no,second,"Laroche, Mr. Joseph Philippe Lemercier",male,25.0,1,2,SC/Paris 2123,41.5792,Missing,C,4,M
311,312,yes,first,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C,5,B

In [5]:
df['Deck'].value_counts()

Deck
M    687
C     59
B     47
D     33
E     32
A     15
F     13
G      4
T      1
Name: count, dtype: int64

In [7]:
# Separate the features (X) from the target we want to predict (y)
# We drop 'Survived' from X because that's our answer key
X = df.drop('Survived', axis=1)

# y contains only the survival status
y = df['Survived']

In [8]:
X

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Deck
0,1,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Missing,S,2,M
1,2,first,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,C
2,3,third,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Missing,S,1,M
3,4,first,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,C
4,5,third,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Missing,S,1,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,second,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,Missing,S,1,M
887,888,first,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1,B
888,889,third,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,Missing,S,4,M
889,890,first,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1,C
890,891,third,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Missing,Q,1,M

In [9]:
y

0       no
1      yes
2      yes
3      yes
4       no
      ...
886     no
887    yes
888     no
889    yes
890     no
Name: Survived, Length: 891, dtype: object

## 3. Data Splitting

In [10]:
# Split data: 80% for training the model and 20% for testing its accuracy
# 'stratify=y' ensures both sets have a similar percentage of survivors
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

## 4. Outlier Handling and Data Cleaning

In [11]:
X_train

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Deck
692,693,third,"Lam, Mr. Ali",male,NaN,0,0,1601,56.4958,Missing,S,1,M
481,482,second,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0000,Missing,S,1,M
527,528,first,"Farthing, Mr. John",male,NaN,0,0,PC 17483,221.7792,C95,S,1,C
855,856,third,"Aks, Mrs. Sam (Leah Rosen)",female,18.0,0,1,392091,9.3500,Missing,S,2,M
801,802,second,"Collyer, Mrs. Harvey (Charlotte Annie Tate)",female,31.0,1,1,C.A. 31921,26.2500,Missing,S,3,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,360,third,"Mockler, Miss. Helen Mary ""Ellie""",female,NaN,0,0,330980,7.8792,Missing,Q,1,M
258,259,first,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,Missing,C,1,M
736,737,third,"Ford, Mrs. Edward (Margaret Ann Watson)",female,48.0,1,3,W./C. 6608,34.3750,Missing,S,5,M
462,463,first,"Gee, Mr. Arthur H",male,47.0,0,0,111320,38.5000,E63,S,1,E
507,508,first,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,0,0,111427,26.5500,Missing,S,1,M

In [12]:
y_train

692    yes
481     no
527     no
855    yes
801    yes
      ...
359    yes
258    yes
736     no
462     no
507    yes
Name: Survived, Length: 712, dtype: object

In [ ]:
#age
mean_age = X_train['Age'].mean()
std_age = X_train['Age'].std()

X_train['Z_score'] = (X_train['Age'] - mean_age) / std_age

musk = (abs(X_train['Z_score']) <= 3)

X_train = X_train[musk]
y_train = y_train[musk]

# fare

fare_Q1 = X_train['Fare'].quantile(0.25)
fare_Q3 = X_train['Fare'].quantile(0.75)

IQR = fare_Q3 - fare_Q1

minimum = max(0 , fare_Q1 - 1.5 * IQR)
maximum = fare_Q3 + 1.5 * IQR

X_train['Fare'] = X_train['Fare'].clip(minimum, maximum)

## 5. Building Preprocessing Pipelines

In [18]:
# numerical
p1 = Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='mean')),
        ('scaler',StandardScaler())
    ]
)

p2 = Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='median')),
        ('scaler',MinMaxScaler())
    ]
)

p1

Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler())])

In [19]:
p2

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('scaler', MinMaxScaler())])

In [14]:
# categories goes one after another via stricly following the order of the input
categories = [['third','second','first']]

In [20]:
#  categorical columns

p3 = Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('encoder',OneHotEncoder(sparse_output=False,drop='first',handle_unknown='ignore'))
    ]
)

p4 = Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('encoder',OrdinalEncoder(categories=categories)),
        ('scaler',MinMaxScaler())
    ]
)
p3

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder',
                 OneHotEncoder(drop='first', handle_unknown='ignore',
                               sparse_output=False))])

In [21]:
p4

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder',
                 OrdinalEncoder(categories=[['third', 'second', 'first']])),
                ('scaler', MinMaxScaler())])

In [16]:
preprocessor = ColumnTransformer(
    transformers=[
        ('pipeline_1',p1,['Age']),
        ('pipeline_2',p2,['Fare','Family_Size']),
        ('pipeline_3',p3,['Embarked','Sex','Deck']),
        ('pipeline_4',p4,['Pclass'])
    ],
    remainder='drop'
)
preprocessor

ColumnTransformer(transformers=[('pipeline_1',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['Age']),
                                ('pipeline_2',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('scaler', MinMaxScaler())]),
                                 ['Fare', 'Family_Size']),
                                ('pipeline_3',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['Embarked', 'Sex', 'Deck']),
                                ('pipeline_4',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OrdinalEncoder(categories=[['third',
                                                                              'second',
                                                                              'first']])),
                                                 ('scaler', MinMaxScaler())]),
                                 ['Pclass'])])

## 6. Label Encoding

In [17]:
le = LabelEncoder()

le.fit(y_train)

y_train = le.transform(y_train)
y_test = le.transform(y_test)

## 7. Model Training

In [22]:
lr_model = Pipeline(
    steps=[
        ('preprocessor',preprocessor),
        ('model',LogisticRegression(class_weight='balanced',max_iter=1000))
    ]
)
lr_model

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('pipeline_1',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['Age']),
                                                 ('pipeline_2',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Fare', 'Family_Size']),
                                                 ('pipeline_3',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strateg...
                                                                   OneHotEncoder(drop='first',
                                                                                 handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Embarked', 'Sex', 'Deck']),
                                                 ('pipeline_4',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OrdinalEncoder(categories=[['third',
                                                                                               'second',
                                                                                               'first']])),
                                                                  ('scaler',
                                                                   MinMaxScaler())]),
                                                  ['Pclass'])])),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [23]:
lr_model.fit(X_train,y_train)

lr_model['model'].coef_
lr_model['model'].intercept_
lr_model['model'].classes_

array([0, 1])

In [24]:
X_test

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family_Size,Deck
565,566,third,"Davies, Mr. Alfred J",male,24.0,2,0,A/4 48871,24.1500,Missing,S,3,M
160,161,third,"Cribb, Mr. John Hatfield",male,44.0,0,1,371362,16.1000,Missing,S,2,M
553,554,third,"Leeni, Mr. Fahim (""Philip Zenni"")",male,22.0,0,0,2620,7.2250,Missing,C,1,M
860,861,third,"Hansen, Mr. Claus Peter",male,41.0,2,0,350026,14.1083,Missing,S,3,M
241,242,third,"Murphy, Miss. Katherine ""Kate""",female,NaN,1,0,367230,15.5000,Missing,Q,2,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,881,second,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,Missing,S,2,M
91,92,third,"Andreasson, Mr. Paul Edvin",male,20.0,0,0,347466,7.8542,Missing,S,1,M
883,884,second,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,Missing,S,1,M
473,474,second,"Jerwan, Mrs. Amin S (Marie Marthe Thuillard)",female,23.0,0,0,SC/AH Basle 541,13.7917,D,C,1,D
637,638,second,"Collyer, Mr. Harvey",male,31.0,1,1,C.A. 31921,26.2500,Missing,S,3,M

In [25]:
# Use the trained model to predict if passengers in the test set survived
y_pred = lr_model.predict(X_test)

# Get the raw probability scores (e.g., 0.85 chance of death, 0.15 chance of survival)
lr_model.predict_proba(X_test)

array([[0.86250724, 0.13749276],
       [0.92185031, 0.07814969],
       [0.74629618, 0.25370382],
       [0.92223345, 0.07776655],
       [0.23460179, 0.76539821],
       [0.41618011, 0.58381989],
       [0.23706975, 0.76293025],
       [0.58977302, 0.41022698],
       [0.52751483, 0.47248517],
       [0.79720633, 0.20279367],
       [0.77216932, 0.22783068],
       [0.82447686, 0.17552314],
       [0.31526778, 0.68473222],
       [0.70897134, 0.29102866],
       [0.41869444, 0.58130556],
       [0.73947197, 0.26052803],
       [0.44218511, 0.55781489],
       [0.8626754 , 0.1373246 ],
       [0.79673722, 0.20326278],
       [0.22398311, 0.77601689],
       [0.8626754 , 0.1373246 ],
       [0.2038076 , 0.7961924 ],
       [0.86351383, 0.13648617],
       [0.43438672, 0.56561328],
       [0.859127  , 0.140873  ],
       [0.03125334, 0.96874666],
       [0.48026201, 0.51973799],
       [0.61935982, 0.38064018],
       [0.79192773, 0.20807227],
       [0.79577908, 0.20422092],
       [0.87999359, 0.12000641],
       [0.05148748, 0.94851252],
       [0.83027804, 0.16972196],
       [0.58930565, 0.41069435],
       [0.78426786, 0.21573214],
       [0.75227552, 0.24772448],
       [0.78351981, 0.21648019],
       [0.39655039, 0.60344961],
       [0.77216932, 0.22783068],
       [0.16732524, 0.83267476],
       [0.81324168, 0.18675832],
       [0.02693536, 0.97306464],
       [0.85616062, 0.14383938],
       [0.13383773, 0.86616227],
       [0.22910955, 0.77089045],
       [0.81948236, 0.18051764],
       [0.86251132, 0.13748868],
       [0.45429667, 0.54570333],
       [0.13192497, 0.86807503],
       [0.11847594, 0.88152406],
       [0.06618753, 0.93381247],
       [0.33801936, 0.66198064],
       [0.21600387, 0.78399613],
       [0.75260273, 0.24739727],
       [0.31213128, 0.68786872],
       [0.84516917, 0.15483083],
       [0.87480419, 0.12519581],
       [0.26766768, 0.73233232],
       [0.26958734, 0.73041266],
       [0.6303831 , 0.3696169 ],
       [0.26200197, 0.73799803],
       [0.2786366 , 0.7213634 ],
       [0.79059389, 0.20940611],
       [0.84521545, 0.15478455],
       [0.48288927, 0.51711073],
       [0.29130497, 0.70869503],
       [0.07302776, 0.92697224],
       [0.87589186, 0.12410814],
       [0.52983669, 0.47016331],
       [0.71059247, 0.28940753],
       [0.09569497, 0.90430503],
       [0.79689912, 0.20310088],
       [0.25712004, 0.74287996],
       [0.03647361, 0.96352639],
       [0.77399653, 0.22600347],
       [0.9208728 , 0.0791272 ],
       [0.88383566, 0.11616434],
       [0.85503949, 0.14496051],
       [0.60116159, 0.39883841],
       [0.29147714, 0.70852286],
       [0.82295956, 0.17704044],
       [0.79804512, 0.20195488],
       [0.77981565, 0.22018435],
       [0.84520352, 0.15479648],
       [0.16600782, 0.83399218],
       [0.37289233, 0.62710767],
       [0.87339807, 0.12660193],
       [0.3622289 , 0.6377711 ],
       [0.32306809, 0.67693191],
       [0.0190158 , 0.9809842 ],
       [0.42977994, 0.57022006],
       [0.42989693, 0.57010307],
       [0.9090994 , 0.0909006 ],
       [0.86269284, 0.13730716],
       [0.58566998, 0.41433002],
       [0.19523014, 0.80476986],
       [0.34301543, 0.65698457],
       [0.77216932, 0.22783068],
       [0.88383566, 0.11616434],
       [0.84130815, 0.15869185],
       [0.71372705, 0.28627295],
       [0.0657748 , 0.9342252 ],
       [0.21597828, 0.78402172],
       [0.08673613, 0.91326387],
       [0.84518947, 0.15481053],
       [0.39508387, 0.60491613],
       [0.64691003, 0.35308997],
       [0.86269284, 0.13730716],
       [0.80831227, 0.19168773],
       [0.45009362, 0.54990638],
       [0.77216932, 0.22783068],
       [0.94883269, 0.05116731],
       [0.84996698, 0.15003302],
       [0.42269691, 0.57730309],
       [0.15136942, 0.84863058],
       [0.77216932, 0.22783068],
       [0.67804184, 0.32195816],
       [0.79036592, 0.20963408],
       [0.84939224, 0.15060776],
       [0.82734709, 0.17265291],
       [0.85459968, 0.14540032],
       [0.25817472, 0.74182528],
       [0.91383034, 0.08616966],
       [0.31489622, 0.68510378],
       [0.80255246, 0.19744754],
       [0.79446933, 0.20553067],
       [0.44321444, 0.55678556],
       [0.38884315, 0.61115685],
       [0.83778788, 0.16221212],
       [0.56753947, 0.43246053],
       [0.85710336, 0.14289664],
       [0.85461154, 0.14538846],
       [0.23460179, 0.76539821],
       [0.77231906, 0.22768094],
       [0.62562372, 0.37437628],
       [0.81373205, 0.18626795],
       [0.04576286, 0.95423714],
       [0.77216932, 0.22783068],
       [0.21598434, 0.78401566],
       [0.86266833, 0.13733167],
       [0.48408142, 0.51591858],
       [0.75663058, 0.24336942],
       [0.34563039, 0.65436961],
       [0.51997153, 0.48002847],
       [0.75448994, 0.24551006],
       [0.65089446, 0.34910554],
       [0.86269284, 0.13730716],
       [0.73824426, 0.26175574],
       [0.0878375 , 0.9121625 ],
       [0.14082539, 0.85917461],
       [0.85006689, 0.14993311],
       [0.65972357, 0.34027643],
       [0.06354362, 0.93645638],
       [0.16579126, 0.83420874],
       [0.65735144, 0.34264856],
       [0.09592645, 0.90407355],
       [0.7328147 , 0.2671853 ],
       [0.85384911, 0.14615089],
       [0.68541427, 0.31458573],
       [0.14882429, 0.85117571],
       [0.31134584, 0.68865416],
       [0.05595871, 0.94404129],
       [0.21598434, 0.78401566],
       [0.09717383, 0.90282617],
       [0.09908372, 0.90091628],
       [0.29169299, 0.70830701],
       [0.8656735 , 0.1343265 ],
       [0.40163083, 0.59836917],
       [0.16637201, 0.83362799],
       [0.31437522, 0.68562478],
       [0.90779051, 0.09220949],
       [0.79689912, 0.20310088],
       [0.47666969, 0.52333031],
       [0.69483004, 0.30516996],
       [0.18649294, 0.81350706],
       [0.8139701 , 0.1860299 ],
       [0.74043546, 0.25956454],
       [0.02858941, 0.97141059],
       [0.79772156, 0.20227844]])

## 8. Evaluation

In [29]:
accuracy = accuracy_score(y_test,y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
precision = precision_score(y_test,y_pred)
print(f"Precision: {precision* 100:.2f}%")
recall = recall_score(y_test,y_pred)
print(f"Recall: {recall* 100:.2f}%")

Accuracy: 75.98%
Precision: 66.67%
Recall: 75.36%