# ML Assignment 02
### Dataset: House Price Prediction Dataset
### Total Marks: 100

---

## Exam Instructions:
1. প্রথমে নিচের cell এ নিজের **নাম** এবং কোর্সে registration করা **ইমেইল** দিবে
2. Question wise numbering করে Text cell রাখবে এবং এর নিচে Code cell থাকবে, চেষ্টা করবে একটি code cell এ একটি question উত্তর দেওয়ার
3. Google Colab এর মধ্যে কোডগুলো করবে
4. এবং সেই ফাইলটি **'Anyone with the link' & 'View' Access** দিয়ে ফাইলটির Shareable Link টি সাবমিট করবে

---

**Question Dataset Link:** https://www.kaggle.com/datasets/prokshitha/home-value-insights

## Student Information

In [426]:
# Fill in your information
name = "Saiyedul Abrar"           # Write your full name here
email = "saiyedul.abrar1430@gmail.com"          # Write your registered email here

print(f"Name  : {name}")
print(f"Email : {email}")

Name  : Saiyedul Abrar
Email : saiyedul.abrar1430@gmail.com

---
## Question 1 (10 Marks)

Load the House Price dataset and display:
- Dataset shape
- First 10 rows
- 5 random samples

In [427]:
# Question 1
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import SGDRegressor
from sklearn.metrics import mean_squared_error,r2_score,root_mean_squared_error,mean_absolute_error
from sklearn.linear_model import LinearRegression

In [428]:
df = pd.read_csv("house_price_regression_dataset.csv")

df.shape

(1000, 8)

In [429]:
print(df.head(10))

   Square_Footage  Num_Bedrooms  Num_Bathrooms  Year_Built  Lot_Size  \
0            1360             2              1        1981  0.599637
1            4272             3              3        2016  4.753014
2            3592             1              2        2016  3.634823
3             966             1              2        1977  2.730667
4            4926             2              1        1993  4.699073
5            3944             5              3        1990  2.475930
6            3671             1              2        2012  4.911960
7            3419             1              1        1972  2.805281
8             630             3              3        1997  1.014286
9            2185             4              2        1981  3.941604

   Garage_Size  Neighborhood_Quality   House_Price
0            0                     5  2.623829e+05
1            1                     6  9.852609e+05
2            0                     9  7.779774e+05
3            1                     8  2.296989e+05
4            0                     8  1.041741e+06
5            2                     8  8.797970e+05
6            0                     1  8.144279e+05
7            1                     1  7.034131e+05
8            1                     8  1.738750e+05
9            2                     5  5.041765e+05

In [430]:
print(df.sample(5))

     Square_Footage  Num_Bedrooms  Num_Bathrooms  Year_Built  Lot_Size  \
663            3266             5              2        1983  3.707807
928            1451             5              3        1972  1.940123
934            3876             1              1        1974  3.625942
518            4798             5              1        1997  3.345072
94             4340             5              3        1962  1.881070

     Garage_Size  Neighborhood_Quality   House_Price
663            2                     7  7.382267e+05
928            1                     8  3.387864e+05
934            0                     5  7.933238e+05
518            2                     1  1.045202e+06
94             0                    10  9.032519e+05

---
## Question 2 (10 Marks)

Handle missing values and perform feature engineering:
- Impute missing numerical values using `SimpleImputer` with mean strategy
- Impute missing categorical values using most frequent strategy
- Drop columns with more than 50% missing values
- Perform train-test split with `test_size=0.2` and `random_state=42`

Display the shape of final train and test sets.

In [431]:
#Question 2
df.isnull().sum()

Square_Footage          0
Num_Bedrooms            0
Num_Bathrooms           0
Year_Built              0
Lot_Size                0
Garage_Size             0
Neighborhood_Quality    0
House_Price             0
dtype: int64

In [432]:
# numerical column
numerical_col= ['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms', 'Year_Built','Lot_Size', 'Garage_Size', 'House_Price']

In [433]:
numerical_col

['Square_Footage',
 'Num_Bedrooms',
 'Num_Bathrooms',
 'Year_Built',
 'Lot_Size',
 'Garage_Size',
 'House_Price']

In [434]:
num_imputer = SimpleImputer(strategy='mean')
df[numerical_col] = num_imputer.fit_transform(df[numerical_col])

In [435]:
#category column
cat_cols=['Neighborhood_Quality']

In [436]:
cat_cols

['Neighborhood_Quality']

In [437]:
cat_imputer = SimpleImputer(strategy='most_frequent')
df[cat_cols] = cat_imputer.fit_transform(df[cat_cols]) # vai category naito
# porer question Neighborhood_Quality category dhore

In [438]:
morethan50 = len(df) * 0.5 # 50 % = 0.5 so total data * 0.5 = 500 data hobe
df = df.dropna(axis=1, thresh=morethan50) # document

In [439]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Square_Footage        1000 non-null   float64
 1   Num_Bedrooms          1000 non-null   float64
 2   Num_Bathrooms         1000 non-null   float64
 3   Year_Built            1000 non-null   float64
 4   Lot_Size              1000 non-null   float64
 5   Garage_Size           1000 non-null   float64
 6   Neighborhood_Quality  1000 non-null   int64
 7   House_Price           1000 non-null   float64
dtypes: float64(7), int64(1)
memory usage: 62.6 KB

In [440]:
df.describe()

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03
mean,2815.422000,2.990000,1.973000,1986.550000,2.778087,1.022000,5.615000,6.188610e+05
std,1255.514921,1.427564,0.820332,20.632916,1.297903,0.814973,2.887059,2.535681e+05
min,503.000000,1.000000,1.000000,1950.000000,0.506058,0.000000,1.000000,1.116269e+05
25%,1749.500000,2.000000,1.000000,1969.000000,1.665946,0.000000,3.000000,4.016482e+05
50%,2862.500000,3.000000,2.000000,1986.000000,2.809740,1.000000,6.000000,6.282673e+05
75%,3849.500000,4.000000,3.000000,2004.250000,3.923317,2.000000,8.000000,8.271413e+05
max,4999.000000,5.000000,3.000000,2022.000000,4.989303,2.000000,10.000000,1.108237e+06

In [441]:
X = df.drop('House_Price', axis=1)
y = df['House_Price']

In [442]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=42)

In [443]:
X_train.shape

(800, 7)

In [444]:
X_test.shape

(200, 7)

In [445]:
y_train.shape

(800,)

In [446]:
y_test.shape

(200,)

---
## Question 3 (20 Marks)

Implement **Simple Linear Regression** using **only NumPy** (no Scikit-Learn allowed):
- Compute slope (`m`) and intercept (`c`) using the Batch Gradient Descent
- Predict values for the test set
- Print the learned `m` and `c` values

Use `Square_Footage` as feature (X) and `House_Price` as target (y).

In [447]:
#Question 3
X = df['Square_Footage'].values
y = df['House_Price'].values

In [448]:
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=42)

In [449]:
def make_prediction(X, y, w, b):
  """Calculates the model output: f(x) = wx + b"""
  m = X.shape[0] # Number of training examples
  pred_list = np.zeros((m,)) # Initialize an array to store results

  for i in range(m):
    # Apply the linear regression formula
    pred_list[i] = w * X[i] + b

  return pred_list

In [450]:
def compute_cost(X, y, w, b):
  """Calculates the Mean Squared Error (MSE) to measure model accuracy"""
  m = X.shape[0]
  cost = 0.0

  for i in range(m):
    prediction = w * X[i] + b # i th feature value
    error = prediction - y[i] # Difference between prediction and actual value. i th target value
    error_squared = error ** 2
    cost = cost + error_squared

  # We divide by 2m for mathematical convenience in gradient calculations
  cost = cost / (2 * m)

  return cost

In [451]:
def calculate_gradient(X, y, w, b):
  """Computes the gradient (direction to move) for w and b"""
  m = X.shape[0]
  dj_dw = 0.0 # Change needed for weight
  dj_db = 0.0 # Change needed for bias

  for i in range(m):
    prediction = w * X[i] + b
    error = prediction - y[i]
    # Multiply error by X[i] for the weight gradient
    dj_dw = dj_dw + (error * X[i])
    # The bias gradient is just the sum of errors
    dj_db = dj_db + error

  return dj_dw / m, dj_db / m

In [452]:
def gradient_descent(X, y, w_input, b_input, max_iter, alpha=0.01):
  """Automates the tuning of w and b to minimize cost"""
  w = w_input
  b = b_input
  cost_memo = []
  iteration = []

  for i in range(max_iter):
    # 1. Calculate the gradients (the slope)
    dj_dw, dj_db = calculate_gradient(X, y, w, b)

    # 2. Update parameters by taking a small step (alpha) against the gradient
    w = w - alpha * dj_dw
    b = b - alpha * dj_db

    # 3. Track progress by saving the cost
    cost = compute_cost(X, y, w, b)
    cost_memo.append(cost)
    iteration.append(i)

    # Log the status every 100 steps
    if i % 100 == 0:
      print(f"Iteration {i}: Cost {cost:0.4f}, w: {w:0.4f}, b: {b:0.4f}")

  return w, b, cost_memo, iteration

In [453]:
w_final, b_final, cost_memo, iter_list = gradient_descent(X_train,y_train,w_input=0,b_input=0,max_iter=10000,alpha=0.0000001)

Iteration 0: Cost 1395712454.6810, w: 205.4978, b: 0.0619
Iteration 100: Cost 806478620.9858, w: 216.6440, b: 0.1548
Iteration 200: Cost 806477817.9427, w: 216.6440, b: 0.2444
Iteration 300: Cost 806477014.9023, w: 216.6440, b: 0.3340
Iteration 400: Cost 806476211.8645, w: 216.6439, b: 0.4236
Iteration 500: Cost 806475408.8293, w: 216.6439, b: 0.5132
Iteration 600: Cost 806474605.7968, w: 216.6439, b: 0.6028
Iteration 700: Cost 806473802.7670, w: 216.6439, b: 0.6925
Iteration 800: Cost 806472999.7398, w: 216.6438, b: 0.7821
Iteration 900: Cost 806472196.7152, w: 216.6438, b: 0.8717
Iteration 1000: Cost 806471393.6934, w: 216.6438, b: 0.9613
Iteration 1100: Cost 806470590.6741, w: 216.6438, b: 1.0509
Iteration 1200: Cost 806469787.6576, w: 216.6437, b: 1.1405
Iteration 1300: Cost 806468984.6436, w: 216.6437, b: 1.2301
Iteration 1400: Cost 806468181.6324, w: 216.6437, b: 1.3197
Iteration 1500: Cost 806467378.6238, w: 216.6437, b: 1.4093
Iteration 1600: Cost 806466575.6178, w: 216.6436, b: 1.4990
Iteration 1700: Cost 806465772.6145, w: 216.6436, b: 1.5886
Iteration 1800: Cost 806464969.6139, w: 216.6436, b: 1.6782
Iteration 1900: Cost 806464166.6159, w: 216.6435, b: 1.7678
Iteration 2000: Cost 806463363.6205, w: 216.6435, b: 1.8574
Iteration 2100: Cost 806462560.6278, w: 216.6435, b: 1.9470
Iteration 2200: Cost 806461757.6378, w: 216.6435, b: 2.0366
Iteration 2300: Cost 806460954.6504, w: 216.6434, b: 2.1262
Iteration 2400: Cost 806460151.6657, w: 216.6434, b: 2.2158
Iteration 2500: Cost 806459348.6836, w: 216.6434, b: 2.3054
Iteration 2600: Cost 806458545.7042, w: 216.6434, b: 2.3950
Iteration 2700: Cost 806457742.7274, w: 216.6433, b: 2.4847
Iteration 2800: Cost 806456939.7533, w: 216.6433, b: 2.5743
Iteration 2900: Cost 806456136.7819, w: 216.6433, b: 2.6639
Iteration 3000: Cost 806455333.8131, w: 216.6433, b: 2.7535
Iteration 3100: Cost 806454530.8469, w: 216.6432, b: 2.8431
Iteration 3200: Cost 806453727.8834, w: 216.6432, b: 2.9327
Iteration 3300: Cost 806452924.9226, w: 216.6432, b: 3.0223
Iteration 3400: Cost 806452121.9644, w: 216.6431, b: 3.1119
Iteration 3500: Cost 806451319.0089, w: 216.6431, b: 3.2015
Iteration 3600: Cost 806450516.0560, w: 216.6431, b: 3.2911
Iteration 3700: Cost 806449713.1058, w: 216.6431, b: 3.3807
Iteration 3800: Cost 806448910.1582, w: 216.6430, b: 3.4703
Iteration 3900: Cost 806448107.2133, w: 216.6430, b: 3.5600
Iteration 4000: Cost 806447304.2710, w: 216.6430, b: 3.6496
Iteration 4100: Cost 806446501.3314, w: 216.6430, b: 3.7392
Iteration 4200: Cost 806445698.3944, w: 216.6429, b: 3.8288
Iteration 4300: Cost 806444895.4601, w: 216.6429, b: 3.9184
Iteration 4400: Cost 806444092.5285, w: 216.6429, b: 4.0080
Iteration 4500: Cost 806443289.5995, w: 216.6429, b: 4.0976
Iteration 4600: Cost 806442486.6731, w: 216.6428, b: 4.1872
Iteration 4700: Cost 806441683.7494, w: 216.6428, b: 4.2768
Iteration 4800: Cost 806440880.8284, w: 216.6428, b: 4.3664
Iteration 4900: Cost 806440077.9100, w: 216.6428, b: 4.4560
Iteration 5000: Cost 806439274.9943, w: 216.6427, b: 4.5456
Iteration 5100: Cost 806438472.0812, w: 216.6427, b: 4.6352
Iteration 5200: Cost 806437669.1708, w: 216.6427, b: 4.7248
Iteration 5300: Cost 806436866.2630, w: 216.6426, b: 4.8144
Iteration 5400: Cost 806436063.3579, w: 216.6426, b: 4.9040
Iteration 5500: Cost 806435260.4555, w: 216.6426, b: 4.9936
Iteration 5600: Cost 806434457.5556, w: 216.6426, b: 5.0833
Iteration 5700: Cost 806433654.6585, w: 216.6425, b: 5.1729
Iteration 5800: Cost 806432851.7640, w: 216.6425, b: 5.2625
Iteration 5900: Cost 806432048.8721, w: 216.6425, b: 5.3521
Iteration 6000: Cost 806431245.9829, w: 216.6425, b: 5.4417
Iteration 6100: Cost 806430443.0964, w: 216.6424, b: 5.5313
Iteration 6200: Cost 806429640.2125, w: 216.6424, b: 5.6209
Iteration 6300: Cost 806428837.3313, w: 216.6424, b: 5.7105
Iteration 6400: Cost 806428034.4527, w: 216.6424, b: 5.8001
Iteration 6500: Cost 806427231.5768, w: 216.6423, b: 5.8897
Iteration 6600: Cost 806426428.7035, w: 216.6423, b: 5.9793
Iteration 6700: Cost 806425625.8329, w: 216.6423, b: 6.0689
Iteration 6800: Cost 806424822.9649, w: 216.6422, b: 6.1585
Iteration 6900: Cost 806424020.0996, w: 216.6422, b: 6.2481
Iteration 7000: Cost 806423217.2370, w: 216.6422, b: 6.3377
Iteration 7100: Cost 806422414.3770, w: 216.6422, b: 6.4273
Iteration 7200: Cost 806421611.5196, w: 216.6421, b: 6.5169
Iteration 7300: Cost 806420808.6649, w: 216.6421, b: 6.6065
Iteration 7400: Cost 806420005.8129, w: 216.6421, b: 6.6961
Iteration 7500: Cost 806419202.9635, w: 216.6421, b: 6.7857
Iteration 7600: Cost 806418400.1167, w: 216.6420, b: 6.8753
Iteration 7700: Cost 806417597.2726, w: 216.6420, b: 6.9649
Iteration 7800: Cost 806416794.4312, w: 216.6420, b: 7.0545
Iteration 7900: Cost 806415991.5924, w: 216.6420, b: 7.1441
Iteration 8000: Cost 806415188.7563, w: 216.6419, b: 7.2337
Iteration 8100: Cost 806414385.9228, w: 216.6419, b: 7.3233
Iteration 8200: Cost 806413583.0920, w: 216.6419, b: 7.4129
Iteration 8300: Cost 806412780.2639, w: 216.6418, b: 7.5025
Iteration 8400: Cost 806411977.4384, w: 216.6418, b: 7.5921
Iteration 8500: Cost 806411174.6155, w: 216.6418, b: 7.6817
Iteration 8600: Cost 806410371.7953, w: 216.6418, b: 7.7713
Iteration 8700: Cost 806409568.9777, w: 216.6417, b: 7.8609
Iteration 8800: Cost 806408766.1628, w: 216.6417, b: 7.9505
Iteration 8900: Cost 806407963.3506, w: 216.6417, b: 8.0401
Iteration 9000: Cost 806407160.5410, w: 216.6417, b: 8.1297
Iteration 9100: Cost 806406357.7341, w: 216.6416, b: 8.2193
Iteration 9200: Cost 806405554.9298, w: 216.6416, b: 8.3089
Iteration 9300: Cost 806404752.1282, w: 216.6416, b: 8.3985
Iteration 9400: Cost 806403949.3292, w: 216.6416, b: 8.4881
Iteration 9500: Cost 806403146.5328, w: 216.6415, b: 8.5777
Iteration 9600: Cost 806402343.7392, w: 216.6415, b: 8.6673
Iteration 9700: Cost 806401540.9482, w: 216.6415, b: 8.7569
Iteration 9800: Cost 806400738.1598, w: 216.6414, b: 8.8465
Iteration 9900: Cost 806399935.3741, w: 216.6414, b: 8.9361

In [454]:
y_pred = make_prediction(X_test,y_test,w_final,b_final)

In [455]:
w_final

np.float64(216.6413949021251)

In [456]:
b_final

np.float64(9.024816940807984)

---
## Question 4 (10 Marks)

Build a **ColumnTransformer** that applies:
- `StandardScaler` on numerical columns: `Square_Footage`, `Num_Bedrooms`, `Num_Bathrooms`
- `OneHotEncoder` on categorical column: `Neighborhood_Quality`

In [457]:
#Question 4
num_features = ['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms']
cat_features = ['Neighborhood_Quality']

In [458]:
preprocessor = ColumnTransformer(
    transformers=[
        ('numerical', StandardScaler(), num_features),
        ('categorical', OneHotEncoder(handle_unknown='ignore'), cat_features)
    ]
)

In [459]:
preprocessor

ColumnTransformer(transformers=[('numerical', StandardScaler(),
                                 ['Square_Footage', 'Num_Bedrooms',
                                  'Num_Bathrooms']),
                                ('categorical',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 ['Neighborhood_Quality'])])

## Question 5 (20 Marks)

Build a complete **Pipeline** using Scikit-Learn that includes:
- The `ColumnTransformer`
- `SGDRegressor` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

In [460]:
# Question 5
X = df.drop('House_Price', axis=1)
y = df['House_Price']

In [461]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [462]:
num_features = ['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms']
cat_features = ['Neighborhood_Quality']

preprocessor = ColumnTransformer(
    transformers=[
        ('numerical', StandardScaler(), num_features),
        ('categorical', OneHotEncoder(handle_unknown='ignore'), cat_features)
    ]
)

In [463]:
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', SGDRegressor(random_state=42))
])

pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numerical', StandardScaler(),
                                                  ['Square_Footage',
                                                   'Num_Bedrooms',
                                                   'Num_Bathrooms']),
                                                 ('categorical',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Neighborhood_Quality'])])),
                ('regressor', SGDRegressor(random_state=42))])

In [464]:
pipeline.predict(X_test.head(10))

array([ 851369.90594294,  507342.81808969,  985831.68390361,
       1022464.73717754,  759809.07504561,  765675.68037077,
       1004527.78475431,  903546.04648129,  797193.07767156,
        888626.74422641])

In [465]:
y_pred = pipeline.predict(X_test)

print(f"RMSE: {round(np.sqrt(mean_squared_error(y_test, y_pred)), 4)}")
print(f"R2 Score: {round(r2_score(y_test, y_pred), 4)}")

RMSE: 29096.4609
R2 Score: 0.9869

In [466]:
y_test = y_test.values

for i in range(10):
    print("Actual =", y_test[i], ", Predicted =", y_pred[i])

Actual = 901000.4882338208 , Predicted = 851369.9059429427
Actual = 494537.5115454976 , Predicted = 507342.8180896923
Actual = 949404.2006657254 , Predicted = 985831.6839036105
Actual = 1040389.0481357794 , Predicted = 1022464.737177539
Actual = 794010.0167336396 , Predicted = 759809.0750456061
Actual = 724033.5604571347 , Predicted = 765675.6803707681
Actual = 998439.2371139774 , Predicted = 1004527.7847543097
Actual = 909713.435000704 , Predicted = 903546.0464812946
Actual = 792681.5184200833 , Predicted = 797193.0776715595
Actual = 947490.777477816 , Predicted = 888626.7442264127

---
## Question 6 (20 Marks)

Implement **Multiple Linear Regression** using **Scikit-Learn**:
- The `ColumnTransformer`
- `LinearRegression` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

In [467]:
# Question 6
X = df.drop('House_Price', axis=1)
y = df['House_Price']

In [468]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [469]:
num_features = ['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms', 'Year_Built', 'Lot_Size', 'Garage_Size']
cat_features = ['Neighborhood_Quality']

preprocessor = ColumnTransformer([
    ('numerical', StandardScaler(), num_features),
    ('categorical', OneHotEncoder(handle_unknown='ignore'), cat_features)
])
preprocessor

ColumnTransformer(transformers=[('numerical', StandardScaler(),
                                 ['Square_Footage', 'Num_Bedrooms',
                                  'Num_Bathrooms', 'Year_Built', 'Lot_Size',
                                  'Garage_Size']),
                                ('categorical',
                                 OneHotEncoder(handle_unknown='ignore'),
                                 ['Neighborhood_Quality'])])

In [470]:
lr_pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('model', LinearRegression())
])
lr_pipe

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numerical', StandardScaler(),
                                                  ['Square_Footage',
                                                   'Num_Bedrooms',
                                                   'Num_Bathrooms',
                                                   'Year_Built', 'Lot_Size',
                                                   'Garage_Size']),
                                                 ('categorical',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Neighborhood_Quality'])])),
                ('model', LinearRegression())])

In [471]:
lr_pipe.fit(X_train, y_train)
lr_pipe.predict(X_test)

array([ 869874.43985062,  493008.02345424,  943543.84812462,
       1032332.23749616,  776180.75134111,  733011.79958511,
        992374.7738462 ,  885753.69473635,  796210.75661298,
        932031.02566724,  759575.27677118,  643243.21722128,
        218320.55554663, 1047581.54346408,  538240.26739267,
        187920.28537942,  457006.05453339,  357462.67375243,
        743176.17078866,  360497.88431372,  774697.17226795,
        478533.32843092,  683664.94174816,  886565.48810257,
        447467.53387711,  397229.69846458,  453149.51518381,
        445248.76489741,  187462.48324061,  492362.53585775,
        276933.35806085,  898368.25236925,  783331.71172706,
        353086.52373155,  479128.89815337,  765993.89270842,
        475329.46778697,  569584.88499466,  303909.36683578,
        151588.28965764,  304635.46373405,  302368.21768526,
        507927.91018213,  310573.17300151, 1081321.60091396,
       1008499.64906303,  760949.23624777,  808691.12902998,
       1026125.4612961 ,  689478.01274357,  284978.18931906,
        750458.26786653,  813188.25490877,  718353.40378151,
        543385.18313455,  803288.16925198,  172555.55052438,
        331287.33809196,  714982.58465589,  217858.0307007 ,
        988537.0571385 ,  377177.19455598,  322321.40768581,
        511728.22277692,  615887.88671897,  555426.01192921,
        478768.74687519,  743988.60590183,  953894.79677336,
        740221.02729354,  474275.36932433,  860877.44473149,
        265783.13292428,  580689.79184691,  676611.58899378,
        729447.92146455,  552250.07849709,  201165.65583261,
        541098.08853107,  881049.26045528,  546181.0913415 ,
        416442.25471825,  536135.94338203,  199128.98207328,
        152602.74615275,  357302.06042423,  966324.8608262 ,
        941100.16820119,  543193.25373174,  233736.53078651,
        933346.03496382,  778322.51821185,  358688.23193299,
        798773.61617782,  700455.01358991, 1060150.15520168,
        758667.0715347 ,  889638.11945842,  852799.3592982 ,
        597458.13563754,  909321.50049143,  865883.0888324 ,
        268677.14260755,  617675.45570585,  447368.48617988,
        924734.87344434,  572695.29926275,  205846.91832579,
        280779.63134303, 1037968.90699716,  821539.43501728,
        415873.98346162,  926820.25800636,  549606.46880501,
        738333.03627806,  906748.93461423,  280874.2342088 ,
        869703.45686565,  240144.6788434 ,  722010.51544628,
        252299.2644053 ,  491362.29967316,  868019.27481649,
        227919.59851013,  331412.10140303,  300434.60671403,
        551721.19317947,  844766.30410327,  960029.68679997,
        587811.38289553,  778232.21845137,  685378.69183094,
        612451.73868856,  698661.42243111,  685009.93890428,
        854402.2961291 ,  513673.04658363,  620192.17149   ,
        665506.16431467,  245942.29527865,  490981.28199084,
        862245.09353404,  338737.21371074,  735426.30340393,
        878814.821028  ,  351641.51332337,  936590.74927071,
        361911.58625575,  691633.66629355,  935320.94323061,
        574406.90063457,  793870.35065332,  942786.43695055,
        892190.96416326, 1050572.80229827,  684761.02297603,
        272995.78929853,  637040.32927796,  982454.34620544,
        754955.33096851,  243956.70947704,  864410.31093157,
        811193.26851073,  667425.81502986, 1009073.91467312,
        961899.53701261,  914258.78843124,  184606.75120861,
        648283.38438377,  858114.58236849,  652359.00383867,
        263044.83465736,  502637.8552843 ,  457798.07914052,
        521917.02649048,  504310.30136465,  624101.54696291,
       1029139.87190982,  673398.14581767,  527288.20587048,
       1000121.70333833,  745524.89332575,  333806.80087096,
        437716.54997038,  556691.86720362,  494046.08776181,
        356932.87699196,  606537.16962122,  570706.40971584,
        334048.77406259,  506313.60120891,  490233.22968404,
        962337.11855559,  925898.49407829,  258477.64971079,
        821046.75129577,  167475.58064599,  977521.22371511,
        438401.14634088,  663560.88303627])

In [472]:
y_pred = lr_pipe.predict(X_test)

print("RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("R2 Score:", r2_score(y_test, y_pred))

RMSE: 10250.310447408403
R2 Score: 0.9983699856153558

In [473]:
y_test = y_test.values

for i in range(10):
    print("Actual =", y_test[i], ", Predicted =", y_pred[i])

Actual = 901000.4882338208 , Predicted = 869874.4398506229
Actual = 494537.5115454976 , Predicted = 493008.0234542353
Actual = 949404.2006657254 , Predicted = 943543.8481246196
Actual = 1040389.0481357794 , Predicted = 1032332.2374961551
Actual = 794010.0167336396 , Predicted = 776180.7513411064
Actual = 724033.5604571347 , Predicted = 733011.7995851052
Actual = 998439.2371139774 , Predicted = 992374.7738462016
Actual = 909713.435000704 , Predicted = 885753.6947363464
Actual = 792681.5184200833 , Predicted = 796210.756612977
Actual = 947490.777477816 , Predicted = 932031.0256672421

---
## Question 7 (10 Marks) (You have to explore the topic and use the equation via Numpy)
### Dont use LLMs , You can use Documentation

Implement **Multiple Linear Regression** using **only NumPy**:
- Pick random 100 datas from the dataset
- Use the Normal Equation: `θ = (XᵀX)⁻¹ Xᵀy`
- Use `Square_Footage`, `Num_Bedrooms`, and `Num_Bathrooms` as features
- Print the learned coefficients (θ values)

In [474]:
# Question 7
df_random = df.sample(100)
df_random

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
300,3201.0,1.0,1.0,1978.0,3.277485,0.0,5,662119.941058
889,3208.0,2.0,3.0,1951.0,4.267684,2.0,2,672640.786296
491,4102.0,1.0,1.0,1975.0,1.824200,2.0,4,838955.453899
263,1639.0,2.0,2.0,2008.0,2.281827,1.0,9,395042.355060
975,2698.0,2.0,3.0,1983.0,1.110597,2.0,4,571367.825279
...,...,...,...,...,...,...,...,...
859,3781.0,2.0,1.0,1989.0,3.164076,0.0,9,792681.518420
384,2068.0,3.0,1.0,1965.0,1.397774,1.0,5,414808.654318
11,2891.0,2.0,3.0,1982.0,3.978440,0.0,2,635097.395920
731,3428.0,1.0,1.0,2011.0,1.235015,1.0,8,710065.561756
627,4323.0,4.0,1.0,2006.0,2.832243,0.0,7,938864.819263

In [475]:
features = ['Square_Footage', 'Num_Bedrooms', 'Num_Bathrooms']

In [476]:
X = df_random[features].values
y = df_random['House_Price'].values

In [477]:
theta = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)

In [478]:
theta

array([  200.965805  ,  9876.43577996, 10765.51855034])

In [479]:
### Alhamdulillah🙂